spring:
  rabbitmq:
    host: ${GRIDCAPA_RABBITMQ_HOST:localhost}
    port: ${GRIDCAPA_RABBITMQ_PORT:5672}
    username: ${GRIDCAPA_RABBITMQ_USERNAME:gridcapa}
    password: ${GRIDCAPA_RABBITMQ_PASSWORD:gridcapa}
  cloud:
    stream:
      bindings:
        dispatchRaoEvents-in-0:
          destination: rao-runners-logs-exchange
        dispatchRaoEvents-out-0:
          group: cse-idcc-task-manager
          destination: task-manager-logs-exchange   # queue: exchange.group-name # final queue name:  task-manager-logs-exchange.cse-idcc-task-manager
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
    function:
      definition: dispatchRaoEvents

client:
  name: cse-idcc-runner
