spring:
  rabbitmq:
    host: ${GRIDCAPA_RABBITMQ_HOST:localhost}
    port: ${GRIDCAPA_RABBITMQ_PORT:5672}
    username: ${GRIDCAPA_RABBITMQ_USERNAME:gridcapa}
    password: ${GRIDCAPA_RABBITMQ_PASSWORD:gridcapa}
  cloud:
    default:
      group: cse-idcc
    stream:
      bindings:
        dispatchRaoEvents-in-0:
          destination: rao-runners-logs-exchange
        dispatchRaoEvents-out-0:
          destination: task-manager-logs-exchange.cse-idcc-task-manager   # queue: task-manager-logs-exchange.cse-idcc-task-manager should match with task manager: exchange.group
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
    function:
      definition: dispatchRaoEvents

client:
  name: cse-idcc-runner
